name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build
      run: powershell -Command "& '.\build.ps1'"