name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: edgarrc/action-7z@v1.0.4
    - name: Run a one-line script
      run: .\build.ps1