name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: warrenbuckley/Setup-MSBuild@v1
    - name: Run a one-line script
      run: .\build.ps1