name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: .\build.ps1